name: sisga

services:
  postgres:
    container_name: sisga_postgres
    image: ${POSTGRES_IMAGE}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  pgadmin:
    container_name: sisga_pgadmin
    image: ${PGADMIN_IMAGE}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_EXTERNAL_PORT}:${PGADMIN_INTERNAL_PORT}"
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:${PGADMIN_INTERNAL_PORT}/misc/ping"]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3

  api:
    container_name: sisga_api
    depends_on:
      postgres:
        condition: service_healthy
      pgadmin:
        condition: service_healthy
    volumes:
      - api:/api
    build: 
      context: ./api/
      args: 
        API_IMAGE: ${API_IMAGE}
    ports:
      - "${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}"
    networks:
      - postgres
    # healthcheck:
    #   test: ["CMD", "curl", "localhost:${API_INTERNAL_PORT}/"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

  frontend:
    container_name: sisga_frontend
    # depends_on:
    #   api:
    #     condition: service_healthy
    depends_on:
      postgres:
        condition: service_healthy
      pgadmin:
        condition: service_healthy
    volumes:
      - frontend:/frontend
    build: 
      context: ./frontend/
      args: 
        FRONTEND_IMAGE: ${FRONTEND_IMAGE}
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:${FRONTEND_INTERNAL_PORT}"
    networks:
      - postgres


networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    api:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: './api'
    frontend:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: './frontend'


